name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install lib postgres
        run: |
          sudo apt update
          sudo apt-get install --yes libpq-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit pypgstac==0.6.3 psycopg["pool"]

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Launch services
        run: docker-compose up -d

      - name: Ingest Stac Items/Collection
        run: |
          pypgstac pgready --dsn postgresql://username:password@0.0.0.0:5439/postgis
          pypgstac load collections data/collections.json --dsn postgresql://username:password@0.0.0.0:5439/postgis --method insert_ignore
          pypgstac load items data/items.json --dsn postgresql://username:password@0.0.0.0:5439/postgis --method ignore

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Benchmark
        run: |
          python -m pip install pip install https://github.com/vincentsarago/stac-api-benchmark/archive/fixResources.zip
          stac-api-benchmark --url http://127.0.0.1:8081 --collection s2_l2a

      - name: Stop services
        run: docker-compose stop
