name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: install lib postgres
        run: |
          sudo apt update
          sudo apt-get install --yes libpq-dev

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pre-commit click pypgstac==0.6.3 psycopg["pool"]

      - name: Launch services
        run: docker-compose up -d stac database

      - name: Ingest Stac Items/Collection
        run: |
          pypgstac pgready --dsn postgresql://username:password@0.0.0.0:5439/postgis
          pypgstac load collections data/collections.json --dsn postgresql://username:password@0.0.0.0:5439/postgis --method insert_ignore
          pypgstac load items data/items.json --dsn postgresql://username:password@0.0.0.0:5439/postgis --method ignore

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Run benchmark
        run: |
          python -m pip install pip install https://github.com/vincentsarago/stac-api-benchmark/archive/fixResources.zip
          stac-api-benchmark --url http://stac:8081 --collection s2_l2a --verbosity ERROR --num-features 20 --max-items 20 > bench.json
          python scripts/format_benchmark.py bench.json > output.json

      - name: Stop services
        run: docker-compose stop

      - name: Store and benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: stac-fastapi-pgstac Benchmarks
          tool: 'smallerIsBetter'
          output-file-path: output.json
          alert-threshold: '130%'
          comment-on-alert: true
          fail-on-alert: true
          # GitHub API token to make a commit comment
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Make a commit on `gh-pages` only if main
          auto-push: ${{ github.ref == 'refs/heads/main' }}
          benchmark-data-dir-path: benchmarks
